name: Code Linting

on:
  workflow_dispatch:
  push:
    paths:
      - '**.php'
  pull_request:
    paths:
      - '**.php'

jobs:
  php-code-linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
<<<<<<< HEAD
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
=======
        uses: actions/checkout@v6
>>>>>>> e35d119ae557fb5cfdc5361b26508dcecc27c7a0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          coverage: none

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run Pint
        run: vendor/bin/pint --test
